const SUPABASE_URL = "https://ncgmrylulcwoctmvncrs.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZ21yeWx1bGN3b2N0bXZuY3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4Mjk3NTgsImV4cCI6MjEwMDQwNTc1OH0.wLgqnvb37Los2R9BpwyhhZw0hhsBd-Zyl4s1gLfkjrc";

window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
